repos:
  - repo: https://github.com/rust-lang/rust-clippy
    rev: v1.77.0
    hooks:
      - id: clippy
        args: ['--all-targets', '--', '-W', 'clippy::all']

  - repo: https://github.com/rust-lang/rustfmt
    rev: v1.7.0
    hooks:
      - id: rustfmt

  - repo: https://github.com/psf/black
    rev: "24.7.0"
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
