pub mod document;
pub mod error;
pub mod page;
pub mod structure;
pub mod pdf_parser;
pub mod index;
pub mod heading_extractor;
pub mod markdown;
pub mod context;
pub mod navigator;
pub mod security;
pub mod audit;
pub mod forms;

pub use document::PdfDocument;
pub use error::{Error, Result};
pub use page::{BoundingBox, ContentRegion, PageMetadata, RegionType};
pub use structure::{DocumentStructure, HeadingNode, TocEntry};
pub use index::{PdfIndex, PageResult};
pub use heading_extractor::{HeadingSection, HierarchicalHeadings};
pub use markdown::MarkdownOutput;
pub use context::{AgentContext, ContextSection};
pub use navigator::PdfNavigator;
pub use security::{PdfPermissions, EncryptionStatus};
pub use audit::{AuditEvent, AuditEventKind};
pub use forms::{PdfFormField, FormFieldType};
